CREATE TABLE EMPLOYEE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NAME varchar(45) DEFAULT NULL,
	LAST_NAME  varchar(45) DEFAULT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DEPARTMENT varchar(45) DEFAULT NULL,
	OFFICE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMPLOYEE_UK_1 (FIRST_NAME, LAST_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci; 