DROP DATABASE IF EXISTS MULTITENANCY_MASTER;

CREATE DATABASE MULTITENANCY_MASTER ;

USE MULTITENANCY_MASTER;

DROP TABLE IF EXISTS MULTITENANCY_MASTER_DATASOURCE;

CREATE TABLE MULTITENANCY_MASTER_DATASOURCE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	DATASOURCE_KEY VARCHAR(50) NOT NULL,
	DATASOURCE_SCHEMA_NAME VARCHAR(50) NOT NULL,
	DATASOURCE_USERNAME VARCHAR(50) NOT NULL,
	DATASOURCE_PASSWORD VARCHAR(50) NOT NULL,
  	PRIMARY KEY(ID),
	UNIQUE KEY MULTITENANCY_MASTER_DATASOURCE_UK_1 (DATASOURCE_KEY,DATASOURCE_SCHEMA_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


INSERT INTO MULTITENANCY_MASTER_DATASOURCE(DATASOURCE_KEY, DATASOURCE_SCHEMA_NAME, DATASOURCE_USERNAME, DATASOURCE_PASSWORD)
VALUES ('tenant1', 'tenant_1', 'root', 'root');
INSERT INTO MULTITENANCY_MASTER_DATASOURCE(DATASOURCE_KEY, DATASOURCE_SCHEMA_NAME, DATASOURCE_USERNAME, DATASOURCE_PASSWORD)
VALUES ('tenant2', 'tenant_2', 'root', 'root');
INSERT INTO MULTITENANCY_MASTER_DATASOURCE(DATASOURCE_KEY, DATASOURCE_SCHEMA_NAME, DATASOURCE_USERNAME, DATASOURCE_PASSWORD)
VALUES ('tenant3', 'tenant_3', 'root', 'root');

DROP DATABASE IF EXISTS tenant1;

CREATE DATABASE tenant1 ;

USE tenant1;

DROP TABLE IF EXISTS EMPLOYESS;

CREATE TABLE EMPLOYEE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NAME varchar(45) DEFAULT NULL,
	LAST_NAME  varchar(45) DEFAULT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DEPARTMENT varchar(45) DEFAULT NULL,
	OFFICE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMPLOYEE_UK_1 (FIRST_NAME, LAST_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci; 

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Debra', 'West', 'dwest0@hc360.com', 'Training', 'New York');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Doris', 'Grant', 'dgrant1@t-online.de', 'Legal', 'New Jersey');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Justin', 'Richardson', 'jrichardson2@ning.com', 'Support', 'Wasington DC');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Ernest', 'Andrews', 'eandrews3@is.gd', 'Research and Development', 'Manhattan');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Rebecca', 'King', 'rking4@spotify.com', 'Research and Development', 'Colorodo');

DROP DATABASE IF EXISTS tenant2;

CREATE DATABASE tenant2 ;

USE tenant2;

DROP TABLE IF EXISTS EMPLOYESS;

CREATE TABLE EMPLOYEE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NAME varchar(45) DEFAULT NULL,
	LAST_NAME  varchar(45) DEFAULT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DEPARTMENT varchar(45) DEFAULT NULL,
	OFFICE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMPLOYEE_UK_1 (FIRST_NAME, LAST_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci; 

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Andrew', 'Taylor', 'ataylor5@ebay.co.uk', 'Engineering', 'Vanadzor');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Christopher', 'Holmes', 'cholmes6@altervista.org', 'Services', 'Gonghe');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Daniel', 'Banks', 'dbanks7@1688.com', 'Accounting', 'Powidz');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Denise', 'Gilbert', 'dgilbert8@cdc.gov', 'Services', 'Ocote Paulino');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Matthew', 'Daniels', 'mdaniels9@wikipedia.org', 'Human Resources', 'Santo Isidro');

DROP DATABASE IF EXISTS tenant3;

CREATE DATABASE tenant3 ;

USE tenant3;

DROP TABLE IF EXISTS EMPLOYESS;

CREATE TABLE EMPLOYEE (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NAME varchar(45) DEFAULT NULL,
	LAST_NAME  varchar(45) DEFAULT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DEPARTMENT varchar(45) DEFAULT NULL,
	OFFICE varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMPLOYEE_UK_1 (FIRST_NAME, LAST_NAME)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci; 

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Clarence', 'Bishop', 'cbishopa@youku.com', 'Human Resources', 'Chornukhy');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Paula', 'Turner', 'pturnerb@abc.net.au', 'Research and Development', 'Il’ya');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Paul', 'Bailey', 'pbaileyc@themeforest.net', 'Services', 'Cocieri');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Paul', 'Gonzalez', 'pgonzalezd@msn.com', 'Human Resources', 'Limon');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Frank', 'Carter', 'fcartere@nationalgeographic.com', 'Legal', 'Urozhaynoye');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Kimberly', 'Palmer', 'kpalmerf@so-net.ne.jp', 'Product Management', 'Heřmanova Huť');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Sharon', 'Boyd', 'sboydg@google.de', 'Research and Development', 'Huangpo');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Tina', 'Brooks', 'tbrooksh@about.me', 'Product Management', 'Tandahimba');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Eugene', 'Patterson', 'epattersoni@wordpress.com', 'Training', 'Danan');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT, OFFICE) VALUES ('Lawrence', 'Gibson', 'lgibsonj@nydailynews.com', 'Sales', 'Nyimba');